### ISSUE TITLE
Crash when adding new 'twirl' (or other UV) node to empty shader (talos-3d branch)

### ISSUE THREAD

**Issue by bploeckelman** [rockbite/talos#163]
Working through the [youtube tutorial series](https://www.youtube.com/watch?v=7deMylejPyw) in the `talos-3d` branch, I'm running into a crash related to a missing uniform when adding the 'twirl' shader node (see the stack trace below). Other 'UV' shader nodes have the same issue. 

This is probably a fairly critical issue to get solved as I'm not sure that it's possible to create new 3d effects at the moment and the only alternative I can think of is to modify the example effects to try to get the desired behavior for a new effect.

I'm happy to make a pull request on this but I'm not familiar enough with the architecture to be confident in a fix. I see the shader body and IO config for the twirl node in `assets/addons/shader/nodes.xml` and it seems like `resources/shaders/gl3/core/defaultSprite.frag.glsl` from Bongo might be involved? Any pointers in the right direction would be appreciated.

```
Exception in thread "main" java.lang.IllegalArgumentException: No uniform with name 'u_textures' in shader
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:303)
	at com.rockbite.bongo.engine.render.PolygonSpriteBatchMultiTextureMULTIBIND.setupMatrices(PolygonSpriteBatchMultiTextureMULTIBIND.java:1822)
	at com.rockbite.bongo.engine.render.PolygonSpriteBatchMultiTextureMULTIBIND.setShader(PolygonSpriteBatchMultiTextureMULTIBIND.java:1856)
	at com.talosvfx.talos.editor.addons.shader.widgets.ShaderBox.draw(ShaderBox.java:69)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.talosvfx.talos.editor.nodes.EmptyWindow.draw(EmptyWindow.java:225)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.talosvfx.talos.editor.nodes.NodeBoard.draw(NodeBoard.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
	at com.talosvfx.talos.TalosMain.render(TalosMain.java:228)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.talosvfx.talos.TalosLauncher.main(TalosLauncher.java:76)
```

**Comment by Tom-Ski** [comment]
Haven't loaded up the shader graph in that branch, but it will be because the shaders are not compatible with that shader. Are you in the discord?

**Comment by Tom-Ski** [comment]
I pushed an update on the branch, (and small change into bongo which you'll need to pull also). Let me know how that goes

**Comment by bploeckelman** [comment]
9dd8aae850a0c8e2826ea9639cf86ea51e80f4a4 and c9f256f8bb179f02d3b8a2e9c91a998386fe7334 fixed this issue. I'm able to create any of the UV node types in the shader graph view now. Thanks!
