### ISSUE TITLE
Crash to conncect nodes

### ISSUE THREAD

**Issue by rdcklinux** [rockbite/talos#32]
System:

- Ubuntu 18.04 (Ubuntu 18.04.3 LTS)
- Java: jdk1.8.0_144 (official from oracle)

Steps:
1. Add **Emiter Node**.
2. Add **Particule Node**.
3. Add **Color Node**.
4. Connect **Color Node** to **Particle Node** at **Drawable** input.
5. Talos Crashes with this traceback:
`
java.lang.ClassCastException: com.rockbite.tools.talos.runtime.values.NumericalValue cannot be cast to com.rockbite.tools.talos.runtime.values.DrawableValue
	at com.rockbite.tools.talos.runtime.values.DrawableValue.set(DrawableValue.java:20)
	at com.rockbite.tools.talos.runtime.modules.Module.fetchInputSlotValue(Module.java:104)
	at com.rockbite.tools.talos.runtime.modules.ParticleModule.getDrawable(ParticleModule.java:85)
	at com.rockbite.tools.talos.runtime.Particle.update(Particle.java:80)
	at com.rockbite.tools.talos.runtime.ParticleEmitterInstance.updateParticles(ParticleEmitterInstance.java:163)
	at com.rockbite.tools.talos.runtime.ParticleEmitterInstance.update(ParticleEmitterInstance.java:142)
	at com.rockbite.tools.talos.runtime.ParticleEffectInstance.update(ParticleEffectInstance.java:60)
	at com.rockbite.tools.talos.editor.widgets.ui.PreviewWidget.act(PreviewWidget.java:255)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:222)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:186)
	at com.rockbite.tools.talos.TalosMain.render(TalosMain.java:120)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:265)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by azakhary** [comment]
Hey, thanks for reporting, this is in the list I think (of the roadmap [here](https://github.com/rockbite/talos/projects/1): 

Hoping to push this as part of 1.0.6

Will come back to ping here when done.

**Comment by JulienBe** [comment]
Hey, I think I have a similar issue

`Exception in thread "main" java.lang.ClassCastException: class com.talosvfx.talos.runtime.values.DrawableValue cannot be cast to class com.talosvfx.talos.runtime.values.NumericalValue (com.talosvfx.talos.runtime.values.DrawableValue and com.talosvfx.talos.runtime.values.NumericalValue are in unnamed module of loader 'app')
	at com.talosvfx.talos.runtime.values.NumericalValue.set(NumericalValue.java:109)
	at com.talosvfx.talos.runtime.modules.AbstractModule.fetchInputSlotValue(AbstractModule.java:120)
	at com.talosvfx.talos.runtime.modules.EmitterModule.getDelay(EmitterModule.java:60)
	at com.talosvfx.talos.runtime.ParticleEmitterInstance.update(ParticleEmitterInstance.java:109)
	at com.talosvfx.talos.runtime.ParticleEffectInstance.update(ParticleEffectInstance.java:89)
	at com.talosvfx.talos.editor.widgets.ui.PreviewWidget.act(PreviewWidget.java:261)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:222)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:186)
	at com.talosvfx.talos.TalosMain.render(TalosMain.java:257)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.talosvfx.talos.TalosLauncher.main(TalosLauncher.java:31)`
