### ISSUE TITLE
Crash on MacOS

### ISSUE THREAD

**Issue by chelinho139** [rockbite/talos#60]
Hi, when I try to open Talos on my mac I get this error:

java -jar talos.1.2.0.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1842)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:450)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:380)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
	at com.talosvfx.talos.TalosLauncher.main(TalosLauncher.java:32)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
	at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:39)
	... 6 more
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by glzlaohuai** [comment]
Same here

**Comment by Tom-Ski** [comment]
You would need to run using 
`java -XstartonFirstThread -jar talos.1.2.0.jar`
