### ISSUE TITLE
application doesn't start

### ISSUE THREAD

**Issue by taluks** [rockbite/talos#71]
1.4.0
1.4.1

```
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
        at org.lwjgl.system.Library.loadSystem(Library.java:164)
        at org.lwjgl.system.Library.loadSystem(Library.java:63)
        at org.lwjgl.system.Library.<clinit>(Library.java:51)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:81)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:91)
        at com.talosvfx.talos.TalosLauncher.main(TalosLauncher.java:33)
```

**Comment by K85** [comment]
i solve this problem by manually copy the library DLLs into the root directory of Talos
![image](https://user-images.githubusercontent.com/10484271/146709300-9699730b-0d97-4c93-a8f9-b651cf799597.png)
