### ISSUE TITLE
editor crashes on deleting some nodes

### ISSUE THREAD

**Issue by thenegativehunter2** [rockbite/talos#82]
i'm using ubuntu. this issue exists from all the three versions i tried (1.4.1, 1.4.0, 1.2.0)
i open the fire example, i delete the emitter node and the software crashes with this in the console :

```
Exception in thread "main" java.lang.NullPointerException
        at com.talosvfx.talos.runtime.Particle.getY(Particle.java:140)
        at com.talosvfx.talos.runtime.render.drawables.TextureRegionDrawable.draw(TextureRegionDrawable.java:47)
        at com.talosvfx.talos.runtime.render.SpriteBatchParticleRenderer.renderParticle(SpriteBatchParticleRenderer.java:93)
        at com.talosvfx.talos.runtime.render.SpriteBatchParticleRenderer.render(SpriteBatchParticleRenderer.java:75)
        at com.talosvfx.talos.runtime.ParticleEffectInstance.render(ParticleEffectInstance.java:121)
        at com.talosvfx.talos.editor.widgets.ui.PreviewWidget.drawContent(PreviewWidget.java:324)
        at com.talosvfx.talos.editor.widgets.ui.ViewportWidget.draw(ViewportWidget.java:152)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
        at com.kotcrab.vis.ui.widget.VisSplitPane.draw(VisSplitPane.java:296)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
        at com.kotcrab.vis.ui.widget.VisSplitPane.draw(VisSplitPane.java:296)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
        at com.talosvfx.talos.TalosMain.render(TalosMain.java:259)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at com.talosvfx.talos.TalosLauncher.main(TalosLauncher.java:33)
```

**Comment by Bogoth** [comment]
It happens in windows too.
